### ISSUE TITLE
Uncaught Invariant Violation: getNodeFromInstance: Invalid argument. 

### ISSUE THREAD

**Issue by kachkaev** [apollographql/meteor-starter-kit#16] opened 2016-07-02 13:37 UTC
I just created a new copy of this project from scratch to see if @stubailo's recent commits solve #12, but saw this:

![screen shot 2016-07-02 at 14 34 44](https://cloud.githubusercontent.com/assets/608862/16540592/266dd25a-4062-11e6-9b70-cff03f896b9f.png)

The form does not work at all so it is not possible to check what graphql returns when you are logged in.

There is a chance that the bug is in [std:accounts-ui](https://atmospherejs.com/std/accounts-ui) rather than in the starter kit itself, but I still report it here because at least a dependency requires an update.

**Comment by rissem** [comment] 2016-07-02 21:10
I'm seeing this as well with a fresh project.

**Comment by gmanfredi** [comment] 2016-07-02 23:33
Ditto for me.

**Comment by yanivnizry** [comment] 2016-07-03 17:23
+1

**Comment by rjpalermo1** [comment] 2016-07-04 23:12
here too....

**Comment by ddddave** [comment] 2016-07-05 03:56
+1

**Comment by ddddave** [comment] 2016-07-05 07:52
I think this has to do with <Accounts.ui.LoginForm /> on line 15 of App.js. When I remove it the error goes away.

...thinking maybe we are loading react in two places, std:accounts-ui loads and via npm, causing a conflict?

**Comment by caseyrieder** [comment] 2016-07-05 16:40
I removed `<Accounts.ui.LoginForm />`, but the error didnt go away

**Comment by stubailo** [comment] 2016-07-05 18:22
Very odd, let me look.

**Comment by kachkaev** [comment] 2016-07-05 23:13
@stubailo great! Any thoughts so far?

**Comment by yanivnizry** [comment] 2016-07-06 05:52
after reinstalling react react-dom and react-addons-pure-render-mixin to version 15.1 resolved the issue for me

**Comment by caseyrieder** [comment] 2016-07-06 14:37
@yanivnizry thanks for the tip. But I'm still getting the same error message

**Comment by rjpalermo1** [comment] 2016-07-08 17:49
??? any updates here?  Want to get started on my project asap with Meteor and would like to use this stack as base...

**Comment by TimMikeladze** [comment] 2016-07-10 05:18
See relevant issue here https://github.com/studiointeract/accounts-ui/issues/60

In the meantime either do `npm i react@15.0.1 react-dom@15.0.1 react-addons-pure-render-mixin@15.0.1` to resolve the error or don't use the std:accounts-ui package.

**Comment by ManuelDeLeon** [comment] 2016-08-27 19:39
@stubailo 
Did you ever figure out the root cause of the problem? I'm getting the same error on another project when I call findDOMNode =/

**Comment by ManuelDeLeon** [comment] 2016-08-29 17:44
@stubailo 

There's a bug in ReactDOMComponentTree.js (getNodeFromInstance) prior to React v15.3.1 that causes this problem. I didn't bother to figure out exactly when it was fixed but it was fixed between 15.0.0 and 15.3.1

In my case I updated React in my app but not the version required by my library. The problem went away as soon as I updated React in my library.

Hope it helps.

**Comment by xavcz** [comment] 2017-03-14 08:23
Closing this issue, it runs well now 👍

**Closed by xavcz** 2017-03-14 08:23 UTC
